spring:
  application:
    name: eureka-server

server:
  port: 8761  # Default port for Eureka server

eureka:
  client:
    registerWithEureka: false  # This service does not register with Eureka
    fetchRegistry: false        # This service does not fetch from the registry

  server:
    enableSelfPreservation: false  # Disable self-preservation for testing
